# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: Build_PS_Win2016
    pool:
      vmImage: vs2017-win2016

    steps:
    - checkout: self
      persistCredentials: true

    - powershell: |
        .\CorporateDeviceEnrollment/CorpDeviceEnrollment_Get.ps1 -TaskList Test -Verbose
      displayName: 'Execute Tests'
      env:
        azureApplicationId: $(azureApplicationId)
        azureApplicationPassword: $(azureApplicationPassword)
        azureSubscriptionId: $(azureSubscriptionId)
        azureTenantId: $(azureTenantId)
        githubRepoToken: $(githubRepoToken)
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/Unit/TestResults.unit.xml'
        testRunTitle: 'PS_Win2016_Unit'
      displayName: 'Publish Unit Test Results'
      condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')

